### ISSUE TITLE
C# demo is not working with C# SDK 0.1.21

### ISSUE THREAD

**Issue by grokify** [grokify/ringcentral-demos-fax-cover-page#1]
The following issue is related to the C# SDK `Request` object's general `multipart/mixed` functionality and does not relate to the specific capabilities used in this demo.
- https://github.com/ringcentral/ringcentral-csharp/issues/36

**Comment by tylerlong** [comment]
I have got fax working with SDK `1.0.0`. Let me update this demo.

**Comment by tylerlong** [comment]
Weird. I cloned the code and run it without modification and it just worked!

Response:

```
{
  "uri" : "https://platform.ringcentral.com/restapi/v1.0/account/37439510/extension/850957020/message-store/607142859021",
  "id" : 607142859021,
  "to" : [ {
    "phoneNumber" : "+16508370092",
    "location" : "South San Francisco, CA",
    "messageStatus" : "Queued"
  } ],
  "type" : "Fax",
  "creationTime" : "2016-05-31T07:15:29.000Z",
  "readStatus" : "Unread",
  "priority" : "Normal",
  "attachments" : [ {
    "id" : 607142859021,
    "uri" : "https://platform.ringcentral.com/restapi/v1.0/account/37439510/extension/850957020/message-store/607142859021/content/607142859021",
    "type" : "RenderedDocument",
    "contentType" : "application/pdf"
  } ],
  "direction" : "Outbound",
  "availability" : "Alive",
  "messageStatus" : "Queued",
  "faxResolution" : "High",
  "faxPageCount" : 0,
  "lastModifiedTime" : "2016-05-31T07:15:29.201Z",
  "coverIndex" : 7
}
```

**Comment by tylerlong** [comment]
Just tested on Mac, and there were indeed issues. Let me investigate and get back here later. So this issue seems to have something to do with Mac.

**Comment by tylerlong** [comment]
I fixed it and submitted PR: https://github.com/grokify/ringcentral-demos-fax-cover-page/pull/2.

The root cause is Mono on Mac doesn't like the hard-coded boundary string: `Boundary_1_14413901_1361871080888`. It thinks that this boundary string is invalid so it throws `System.ArgumentException`.

**Comment by grokify** [comment]
@tylerlong It's working with C# SDK `1.0.0-alpha2` for me now. Thanks!
