### ISSUE TITLE
Add a demo for Node.js

### ISSUE THREAD

**Issue by tylerlong** [grokify/ringcentral-demos-fax-cover-page#3]
Here is some sample code: https://github.com/tylerlong/rc-commander/blob/master/rc-fax.js

We can just copy and paste to create this demo quickly.

**Comment by tylerlong** [comment]
PR Created: https://github.com/grokify/ringcentral-demos-fax-cover-page/pull/4

**Comment by grokify** [comment]
PR verified and accepted.

Added support for RingCentral user extension in authorization call.
